<script type="text/javascript" src="//code.jquery.com/jquery-1.12.4.js" />
<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" />
<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.4.1/js/dataTables.buttons.min.js" />
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.4.1/js/buttons.flash.min.js" />
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" />
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js" />
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js" />
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.4.1/js/buttons.html5.min.js" />
<script type="text/javascript" src="//cdn.datatables.net/buttons/1.4.1/js/buttons.print.min.js" />